apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-devops-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gke-devops-app
  template:
    metadata:
      labels:
        app: gke-devops-app
    spec:
      containers:
        - name: gke-devops-app
          image: gke-devops-app
          ports:
            - containerPort: 80
