apiVersion: v1
kind: Service
metadata:
  name: gke-devops-service
  labels:
    app: gke-devops-app
spec:
  type: LoadBalancer
  selector:
    app: gke-devops-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
